// Package core provides the main token acquisition orchestration for the Token Broker.
package core

import (
	"context"
	"time"

	pkgauth "github.com/rossoctl/operator/pkg/oauth"
)

// SessionStore manages OAuth sessions and their lifecycle.
type SessionStore interface {
	// CreateSession creates a new session with a provided session key and backend redirect URL.
	CreateSession(sessionKey, userID, backendRedirectURL string) error

	// GetSession retrieves a session by its key.
	GetSession(sessionKey string) (*Session, error)

	// GetSessionByState retrieves a session by its OAuth state parameter.
	GetSessionByState(state string) (*Session, error)

	// ValidateSession checks if a session exists and belongs to the specified user.
	ValidateSession(sessionKey, userID string) error

	// EndSession terminates a session and releases all resources.
	EndSession(sessionKey string) error

	// ExpireSession marks a session as expired and fails all pending requests.
	ExpireSession(sessionKey string)

	// ResetSessionTimer resets the idle timeout timer for a session.
	ResetSessionTimer(sessionKey string)

	// StartSessionTimer starts the idle timeout timer for a session.
	StartSessionTimer(sessionKey string)
}

// TokenCache stores and retrieves access tokens per session and resource server.
type TokenCache interface {
	// GetToken retrieves a cached token for a session and resource server.
	// Returns the token and true if found and not expired, empty string and false otherwise.
	GetToken(sessionKey, resourceURL string) (token string, found bool)

	// SetToken stores a token for a session and resource server.
	SetToken(sessionKey, resourceURL, token string) error

	// DeleteToken removes a token from the cache.
	DeleteToken(sessionKey, resourceURL string)
}

// OAuthDiscoverer performs OAuth discovery against a resource server.
// Updated to support the new architecture where Token Broker is the OAuth client.
type OAuthDiscoverer interface {
	// SendSyntheticRequest sends an unauthenticated resource request to trigger OAuth elicitation.
	// Returns true if the server responds with 401, false otherwise.
	// This is optional and used for validation purposes.
	SendSyntheticRequest(ctx context.Context, resourceURL string) (is401 bool, err error)

	// DiscoverEndpoints discovers OAuth endpoints and scopes from resource server's .well-known metadata.
	// This is ALWAYS called - there is no configured mode.
	// Returns: authorizationEndpoint, tokenEndpoint, scopes, error
	DiscoverEndpoints(ctx context.Context, resourceURL string) (authEndpoint, tokenEndpoint string, scopes []string, err error)
}

// Clock provides time-related operations for testability.
type Clock interface {
	// Now returns the current time.
	Now() time.Time

	// After returns a channel that receives the current time after the specified duration.
	After(d time.Duration) <-chan time.Time
}

// Session represents an OAuth session.
type Session struct {
	SessionKey                string
	UserID                    string
	BackendSessionRedirectURL string // Where to redirect user after OAuth completion
	CreatedAt                 time.Time
	LastPollAt                time.Time
	ExpirationDeadline        time.Time

	// Concurrency control
	AcquisitionSemaphore Semaphore

	// Event coordination
	EventWaiters chan Event
	TokenWaiters map[string][]chan TokenResult // resourceURL -> waiters

	// Done is closed when the session is ended or expired, to unblock waiters.
	Done chan struct{}

	// Active OAuth transaction
	ActiveOAuthTx *OAuthTransaction
}

// Semaphore provides mutual exclusion for token acquisition per session.
type Semaphore interface {
	// Acquire acquires the semaphore, blocking until available or context is cancelled.
	Acquire(ctx context.Context) error

	// Release releases the semaphore.
	Release()
}

// OAuthTransaction represents an active OAuth flow.
// Updated to support the new architecture where Token Broker generates PKCE
// and exchanges tokens directly with the OAuth provider.
type OAuthTransaction struct {
	ResourceURL   string
	AuthEndpoint  string   // Discovered from resource server .well-known
	TokenEndpoint string   // Discovered from resource server .well-known
	Scopes        []string // Discovered from resource server .well-known

	// PKCE generated by Token Broker
	PKCE         *pkgauth.PKCEChallenge
	CodeVerifier string // Convenience field (same as PKCE.Verifier)

	// State parameter for OAuth flow
	State string // Generated by Token Broker, used to map callback to session

	// Callback URL (Token Broker's own callback URL, not Backend's)
	CallbackURL string

	// Authorization URL built by Token Broker
	AuthURL string

	// Flow status, one of the OAuthTxStatus* constants.
	Status         string
	CompletionChan chan OAuthCompletion
}

// OAuth transaction status values for OAuthTransaction.Status.
const (
	OAuthTxStatusWaitingCode = "waiting_code"
	OAuthTxStatusCompleted       = "completed"
	OAuthTxStatusFailed          = "failed"
)

// OAuthCompletion represents the result of an OAuth flow.
type OAuthCompletion struct {
	Code  string
	State string
	Error error
}

// Event represents an event sent to the Backend via long-poll.
type Event struct {
	Type string `json:"type"` // "oauth_url_ready" | "error"

	// For oauth_url_ready (Backend should redirect frontend to OAuth provider)
	AuthURL string `json:"auth_url,omitempty"`

	// For error
	Message string `json:"message,omitempty"`
	Code    string `json:"code,omitempty"`
}

// TokenResult represents the result of a token acquisition.
type TokenResult struct {
	Token string
	Error error
}

// RealClock implements Clock using the standard time package.
type RealClock struct{}

// Now returns the current time.
func (c *RealClock) Now() time.Time {
	return time.Now()
}

// After returns a channel that receives the current time after the specified duration.
func (c *RealClock) After(d time.Duration) <-chan time.Time {
	return time.After(d)
}
