{{- if .Values.bundleService.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: bundle-service
  name: bundle-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: bundle-service
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
{{- end -}}
