{{- if and .Values.rbac.enable .Values.bundleService.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: bundle-service
  name: {{ .Values.bundleService.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
